FROM node:20-alpine AS builder

WORKDIR /app

COPY server/package.json server/tsconfig.json ./
RUN npm install

COPY prisma/ ../prisma/
COPY server/src/ ./src/

RUN npx prisma generate
RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY server/package.json ./
COPY prisma/ ../prisma/

EXPOSE 5000

CMD ["node", "dist/index.js"]
